

spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    cache: false
    expose-request-attributes: true
    request-context-attribute: request
  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    port: 465
    protocol: smtps
    username: xxxx@qq.com
    password: xxxx
    properties:
      mail:
        stmp:
          ssl:
            enable: true
server:
  port: 8080
  servlet:
    session:
      cookie:
        path: /
        http-only: true
        name: JSESSIONID

httpclient:
  maxTotal: 300
  defaultMaxPerRoute: 50
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 5000
  staleConnectionCheckEnabled: true
bot:
  #连接类型，可选：ws, ws-reverse,http(开发中)
  type: ws
  #go-cqhttp的地址,要附带协议(如ws://127.0.0.1:6700)
  url: ws://xxx.xxx.xx.xx:xx
  #go-cqhttp配置中的access_token
  accessToken: 'xxxx'

# chatGpt apikey https://platform.openai.com/account/api-key 这里获取
chatGpt:
  apiKey: xxx

env:
  path: classpath:/env.properties

chrome:
  headless: true
  timeout: 150
  driver:
    path: /workspace/bot/jd-qinglong/chromedriver.exe
go-cqhttp:
  dir: /workspace/bot/go-cqhttp
op:
  timeout: 60
SE_NODE_MAX_SESSIONS: 10
login:
  type: phone

selenium:
  hub:
    url: http://localhost:4444/wd/hub
    status:
      url: http://localhost:4444/status
