


env:
  path: classpath:/env.properties
spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    cache: false
    expose-request-attributes: true
    request-context-attribute: request
server:
  port: 8080
  servlet:
    session:
      cookie:
        path: /

bot:
  type: ws  #连接类型，可选：ws, ws-reverse,http(开发中)
  url: ws:// #go-cqhttp的地址,要附带协议(如ws://127.0.0.1:6700)
  accessToken: '' #go-cqhttp配置中的access_token




#
#chrome.headless=true
#env.path=/env.properties
#SE_NODE_MAX_SESSIONS=10
#op.timeout=60
#chrome.timeout=150